include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_returning_null: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    comment_references: true
    control_flow_in_finally: true
    diagnostic_describe_all_properties: true
    empty_statements: true
    hash_and_equals: true
    join_return_with_assignment: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    null_closures: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_expression_function_bodies: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_method_calls: true
    prefer_spread_collections: true
    provide_deprecation_message: true
    public_member_api_docs: false
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    valid_regexps: true
